services:
  influxdb:
    image: influxdb:2.7 # Use the latest 2.x version
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=iot_project
      - DOCKER_INFLUXDB_INIT_BUCKET=smart_city
      - DOCKER_INFLUXDB_INIT_RETENTION=30d

  telegraf:
      image: telegraf
      container_name: telegraf
      restart: always
      volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      depends_on:
        - influxdb
        - mqtt-broker
      ports:
        - '8125:8125'    

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./iot_project_nodered/data:/data
    environment:
      - TZ=UTC

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9002:9001" # WebSocket support
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./iot_project_mosquitto_config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:
  mosquitto_data: